import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import Header from "./components/organism/header/Header";
import Footer from "./components/organism/Footer";

<link
  href="https://cdn.jsdelivr.net/gh/rastikerdar/vazirmatn@v33.003/Vazirmatn-font-face.css"
  rel="stylesheet"
  type="text/css"
/>;

export const metadata: Metadata = {
  title: "Zi Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" className="dark">
      <body>
        {" "}
        <Header />
        <Providers>{children}</Providers>
        <Footer />
      </body>
    </html>
  );
}
